import type { Product, Category, Collection, Review, SiteSettings } from './types'

export const mockCategories: Category[] = [
  { id: 'cat-1', name: 'Dresses', slug: 'dresses', parent_id: null, image_url: null, sort_order: 0, is_active: true },
  { id: 'cat-2', name: 'Tops', slug: 'tops', parent_id: null, image_url: null, sort_order: 1, is_active: true },
  { id: 'cat-3', name: 'Sets', slug: 'sets', parent_id: null, image_url: null, sort_order: 2, is_active: true },
  { id: 'cat-4', name: 'Bottoms', slug: 'bottoms', parent_id: null, image_url: null, sort_order: 3, is_active: true },
  { id: 'cat-5', name: 'Bodysuits', slug: 'bodysuits', parent_id: 'cat-2', image_url: null, sort_order: 0, is_active: true },
]

export const mockCollections: Collection[] = [
  { id: 'col-1', name: 'New Arrivals', slug: 'new-arrivals', description: 'The latest from theKlane', image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=1200&q=80', sort_order: 0, is_active: true },
  { id: 'col-2', name: 'Summer Drop', slug: 'summer-drop', description: 'Light, airy pieces for warm days', image_url: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=1200&q=80', sort_order: 1, is_active: true },
  { id: 'col-3', name: 'Best Sellers', slug: 'best-sellers', description: 'The pieces everyone loves', image_url: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=1200&q=80', sort_order: 2, is_active: true },
]

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Linen Midi Dress',
    slug: 'linen-midi-dress',
    description: 'A relaxed-fit midi dress crafted from breathable linen. Perfect for warm evenings and effortless days out. The slightly oversized silhouette drapes beautifully, offering comfort without sacrificing style.',
    materials: '100% Belgian Linen',
    care_instructions: 'Hand wash cold. Lay flat to dry. Iron on low.',
    category_id: 'cat-1',
    base_price: 198,
    sale_price: 148,
    is_active: true,
    is_featured: true,
    is_new_arrival: false,
    is_on_sale: true,
    track_inventory: true,
    created_at: '2024-01-15T00:00:00Z',
    product_images: [
      { id: 'img-1a', product_id: 'prod-1', url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80', thumb_url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&q=80', position: 0, is_primary: true },
      { id: 'img-1b', product_id: 'prod-1', url: 'https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=800&q=80', thumb_url: 'https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=400&q=80', position: 1, is_primary: false },
    ],
    product_variants: [
      { id: 'var-1a', product_id: 'prod-1', sku: 'LMD-XS-IVO', size: 'XS', color: 'Ivory', price_override: null, stock_quantity: 4, low_stock_threshold: 5 },
      { id: 'var-1b', product_id: 'prod-1', sku: 'LMD-S-IVO', size: 'S', color: 'Ivory', price_override: null, stock_quantity: 12, low_stock_threshold: 5 },
      { id: 'var-1c', product_id: 'prod-1', sku: 'LMD-M-IVO', size: 'M', color: 'Ivory', price_override: null, stock_quantity: 8, low_stock_threshold: 5 },
      { id: 'var-1d', product_id: 'prod-1', sku: 'LMD-L-IVO', size: 'L', color: 'Ivory', price_override: null, stock_quantity: 0, low_stock_threshold: 5 },
    ],
  },
  {
    id: 'prod-2',
    name: 'Asymmetric Cut-Out Top',
    slug: 'asymmetric-cut-out-top',
    description: 'A statement top with a bold asymmetric hem and subtle cut-out detail. Wear it with high-waist trousers or a flowing skirt for an editorial look.',
    materials: '95% Viscose, 5% Elastane',
    care_instructions: 'Machine wash gentle, cold. Do not tumble dry.',
    category_id: 'cat-2',
    base_price: 128,
    sale_price: null,
    is_active: true,
    is_featured: true,
    is_new_arrival: true,
    is_on_sale: false,
    track_inventory: true,
    created_at: '2024-02-20T00:00:00Z',
    product_images: [
      { id: 'img-2a', product_id: 'prod-2', url: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=80', thumb_url: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400&q=80', position: 0, is_primary: true },
      { id: 'img-2b', product_id: 'prod-2', url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80', thumb_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&q=80', position: 1, is_primary: false },
    ],
    product_variants: [
      { id: 'var-2a', product_id: 'prod-2', sku: 'ACT-XS-BLK', size: 'XS', color: 'Black', price_override: null, stock_quantity: 6, low_stock_threshold: 3 },
      { id: 'var-2b', product_id: 'prod-2', sku: 'ACT-S-BLK', size: 'S', color: 'Black', price_override: null, stock_quantity: 10, low_stock_threshold: 3 },
      { id: 'var-2c', product_id: 'prod-2', sku: 'ACT-M-BLK', size: 'M', color: 'Black', price_override: null, stock_quantity: 7, low_stock_threshold: 3 },
      { id: 'var-2d', product_id: 'prod-2', sku: 'ACT-L-BLK', size: 'L', color: 'Black', price_override: null, stock_quantity: 3, low_stock_threshold: 3 },
    ],
  },
  {
    id: 'prod-3',
    name: 'Satin Co-Ord Set',
    slug: 'satin-co-ord-set',
    description: 'A luxury satin two-piece featuring a cropped blazer and wide-leg trousers. The fluid drape and rich sheen make this set an instant showstopper for any occasion.',
    materials: '100% Polyester Satin',
    care_instructions: 'Dry clean only.',
    category_id: 'cat-3',
    base_price: 298,
    sale_price: null,
    is_active: true,
    is_featured: true,
    is_new_arrival: true,
    is_on_sale: false,
    track_inventory: true,
    created_at: '2024-03-01T00:00:00Z',
    product_images: [
      { id: 'img-3a', product_id: 'prod-3', url: 'https://images.unsplash.com/photo-1566206091558-7f218b696731?w=800&q=80', thumb_url: 'https://images.unsplash.com/photo-1566206091558-7f218b696731?w=400&q=80', position: 0, is_primary: true },
      { id: 'img-3b', product_id: 'prod-3', url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80', thumb_url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&q=80', position: 1, is_primary: false },
    ],
    product_variants: [
      { id: 'var-3a', product_id: 'prod-3', sku: 'SCS-S-CRM', size: 'S', color: 'Cream', price_override: null, stock_quantity: 5, low_stock_threshold: 3 },
      { id: 'var-3b', product_id: 'prod-3', sku: 'SCS-M-CRM', size: 'M', color: 'Cream', price_override: null, stock_quantity: 4, low_stock_threshold: 3 },
      { id: 'var-3c', product_id: 'prod-3', sku: 'SCS-L-CRM', size: 'L', color: 'Cream', price_override: null, stock_quantity: 2, low_stock_threshold: 3 },
    ],
  },
  {
    id: 'prod-4',
    name: 'Wrap Mini Skirt',
    slug: 'wrap-mini-skirt',
    description: 'A chic wrap-style mini skirt with a self-tie waist. Effortlessly transitions from daytime errands to evening outings. The clean lines and structured fabric give it a polished finish.',
    materials: '80% Cotton, 20% Polyester',
    care_instructions: 'Machine wash cold. Tumble dry low.',
    category_id: 'cat-4',
    base_price: 118,
    sale_price: 88,
    is_active: true,
    is_featured: false,
    is_new_arrival: true,
    is_on_sale: true,
    track_inventory: true,
    created_at: '2024-03-10T00:00:00Z',
    product_images: [
      { id: 'img-4a', product_id: 'prod-4', url: 'https://images.unsplash.com/photo-1603217192634-61068e4d4bf9?w=800&q=80', thumb_url: 'https://images.unsplash.com/photo-1603217192634-61068e4d4bf9?w=400&q=80', position: 0, is_primary: true },
      { id: 'img-4b', product_id: 'prod-4', url: 'https://images.unsplash.com/photo-1518462592603-0b44b0c8d414?w=800&q=80', thumb_url: 'https://images.unsplash.com/photo-1518462592603-0b44b0c8d414?w=400&q=80', position: 1, is_primary: false },
    ],
    product_variants: [
      { id: 'var-4a', product_id: 'prod-4', sku: 'WMS-XS-SND', size: 'XS', color: 'Sand', price_override: null, stock_quantity: 8, low_stock_threshold: 4 },
      { id: 'var-4b', product_id: 'prod-4', sku: 'WMS-S-SND', size: 'S', color: 'Sand', price_override: null, stock_quantity: 11, low_stock_threshold: 4 },
      { id: 'var-4c', product_id: 'prod-4', sku: 'WMS-M-SND', size: 'M', color: 'Sand', price_override: null, stock_quantity: 9, low_stock_threshold: 4 },
      { id: 'var-4d', product_id: 'prod-4', sku: 'WMS-L-SND', size: 'L', color: 'Sand', price_override: null, stock_quantity: 6, low_stock_threshold: 4 },
    ],
  },
  {
    id: 'prod-5',
    name: 'Structured Bodysuit',
    slug: 'structured-bodysuit',
    description: 'A sculpting bodysuit with a built-in underwire and adjustable straps. Designed to be worn as a base layer or as a statement piece on its own.',
    materials: '85% Nylon, 15% Spandex',
    care_instructions: 'Hand wash only.',
    category_id: 'cat-5',
    base_price: 98,
    sale_price: null,
    is_active: true,
    is_featured: true,
    is_new_arrival: false,
    is_on_sale: false,
    track_inventory: true,
    created_at: '2024-01-08T00:00:00Z',
    product_images: [
      { id: 'img-5a', product_id: 'prod-5', url: 'https://images.unsplash.com/photo-1617019114583-affb34d1b3cd?w=800&q=80', thumb_url: 'https://images.unsplash.com/photo-1617019114583-affb34d1b3cd?w=400&q=80', position: 0, is_primary: true },
      { id: 'img-5b', product_id: 'prod-5', url: 'https://images.unsplash.com/photo-1524253482453-3fed8d2fe12b?w=800&q=80', thumb_url: 'https://images.unsplash.com/photo-1524253482453-3fed8d2fe12b?w=400&q=80', position: 1, is_primary: false },
    ],
    product_variants: [
      { id: 'var-5a', product_id: 'prod-5', sku: 'SBS-XS-BLK', size: 'XS', color: 'Black', price_override: null, stock_quantity: 14, low_stock_threshold: 4 },
      { id: 'var-5b', product_id: 'prod-5', sku: 'SBS-S-BLK', size: 'S', color: 'Black', price_override: null, stock_quantity: 18, low_stock_threshold: 4 },
      { id: 'var-5c', product_id: 'prod-5', sku: 'SBS-M-BLK', size: 'M', color: 'Black', price_override: null, stock_quantity: 12, low_stock_threshold: 4 },
    ],
  },
  {
    id: 'prod-6',
    name: 'Draped Maxi Dress',
    slug: 'draped-maxi-dress',
    description: 'A show-stopping maxi dress with a fluid drape and deep V-neckline. The one-shoulder silhouette creates an effortless editorial moment for any occasion.',
    materials: '100% Cupro',
    care_instructions: 'Dry clean recommended.',
    category_id: 'cat-1',
    base_price: 248,
    sale_price: null,
    is_active: true,
    is_featured: true,
    is_new_arrival: true,
    is_on_sale: false,
    track_inventory: true,
    created_at: '2024-03-20T00:00:00Z',
    product_images: [
      { id: 'img-6a', product_id: 'prod-6', url: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&q=80', thumb_url: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400&q=80', position: 0, is_primary: true },
      { id: 'img-6b', product_id: 'prod-6', url: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&q=80', thumb_url: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&q=80', position: 1, is_primary: false },
    ],
    product_variants: [
      { id: 'var-6a', product_id: 'prod-6', sku: 'DMD-XS-MRN', size: 'XS', color: 'Mocha', price_override: null, stock_quantity: 3, low_stock_threshold: 3 },
      { id: 'var-6b', product_id: 'prod-6', sku: 'DMD-S-MRN', size: 'S', color: 'Mocha', price_override: null, stock_quantity: 5, low_stock_threshold: 3 },
      { id: 'var-6c', product_id: 'prod-6', sku: 'DMD-M-MRN', size: 'M', color: 'Mocha', price_override: null, stock_quantity: 4, low_stock_threshold: 3 },
    ],
  },
  {
    id: 'prod-7',
    name: 'Ribbed Knit Midi Skirt',
    slug: 'ribbed-knit-midi-skirt',
    description: 'A sleek ribbed-knit midi skirt with a flattering stretch fabric. Pairs seamlessly with our Structured Bodysuit or any fitted top.',
    materials: '60% Cotton, 35% Polyester, 5% Spandex',
    care_instructions: 'Machine wash gentle, cold.',
    category_id: 'cat-4',
    base_price: 108,
    sale_price: null,
    is_active: true,
    is_featured: false,
    is_new_arrival: true,
    is_on_sale: false,
    track_inventory: true,
    created_at: '2024-03-25T00:00:00Z',
    product_images: [
      { id: 'img-7a', product_id: 'prod-7', url: 'https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=800&q=80', thumb_url: 'https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=400&q=80', position: 0, is_primary: true },
      { id: 'img-7b', product_id: 'prod-7', url: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=800&q=80', thumb_url: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400&q=80', position: 1, is_primary: false },
    ],
    product_variants: [
      { id: 'var-7a', product_id: 'prod-7', sku: 'RKS-XS-BLK', size: 'XS', color: 'Black', price_override: null, stock_quantity: 9, low_stock_threshold: 4 },
      { id: 'var-7b', product_id: 'prod-7', sku: 'RKS-S-BLK', size: 'S', color: 'Black', price_override: null, stock_quantity: 12, low_stock_threshold: 4 },
      { id: 'var-7c', product_id: 'prod-7', sku: 'RKS-M-BLK', size: 'M', color: 'Black', price_override: null, stock_quantity: 7, low_stock_threshold: 4 },
      { id: 'var-7d', product_id: 'prod-7', sku: 'RKS-L-BLK', size: 'L', color: 'Black', price_override: null, stock_quantity: 5, low_stock_threshold: 4 },
    ],
  },
  {
    id: 'prod-8',
    name: 'Blazer Dress',
    slug: 'blazer-dress',
    description: 'A power-dressing blazer dress with a structured shoulder and gold-tone button fastening. Perfect for boardroom days and dinner dates alike.',
    materials: '70% Wool, 30% Polyester',
    care_instructions: 'Dry clean only.',
    category_id: 'cat-1',
    base_price: 278,
    sale_price: 198,
    is_active: true,
    is_featured: true,
    is_new_arrival: false,
    is_on_sale: true,
    track_inventory: true,
    created_at: '2024-01-20T00:00:00Z',
    product_images: [
      { id: 'img-8a', product_id: 'prod-8', url: 'https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?w=800&q=80', thumb_url: 'https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?w=400&q=80', position: 0, is_primary: true },
      { id: 'img-8b', product_id: 'prod-8', url: 'https://images.unsplash.com/photo-1572804013427-4d7ca7268217?w=800&q=80', thumb_url: 'https://images.unsplash.com/photo-1572804013427-4d7ca7268217?w=400&q=80', position: 1, is_primary: false },
    ],
    product_variants: [
      { id: 'var-8a', product_id: 'prod-8', sku: 'BZD-XS-CHR', size: 'XS', color: 'Charcoal', price_override: null, stock_quantity: 2, low_stock_threshold: 3 },
      { id: 'var-8b', product_id: 'prod-8', sku: 'BZD-S-CHR', size: 'S', color: 'Charcoal', price_override: null, stock_quantity: 4, low_stock_threshold: 3 },
      { id: 'var-8c', product_id: 'prod-8', sku: 'BZD-M-CHR', size: 'M', color: 'Charcoal', price_override: null, stock_quantity: 3, low_stock_threshold: 3 },
    ],
  },
]

export const mockReviews: Review[] = [
  { id: 'rev-1', author: 'Amara K.', rating: 5, body: 'Absolutely stunning. The fabric quality exceeded my expectations, it feels luxurious and the fit is perfect. I have received so many compliments wearing theKlane.', created_at: '2024-03-01T00:00:00Z' },
  { id: 'rev-2', author: 'Zoe M.', rating: 5, body: 'I ordered the Linen Midi Dress and it arrived beautifully packaged. The color is even more gorgeous in person. Will definitely be ordering again!', created_at: '2024-02-15T00:00:00Z' },
  { id: 'rev-3', author: 'Isabelle T.', rating: 5, body: 'theKlane is my new favourite brand. The pieces are timeless and incredibly well-made. Customer service was also wonderful when I needed help with sizing.', created_at: '2024-01-28T00:00:00Z' },
  { id: 'rev-4', author: 'Naomi R.', rating: 5, body: 'The Satin Co-Ord Set is a dream. I wore it to a gala and felt like I stepped out of a fashion editorial. Worth every penny.', created_at: '2024-03-10T00:00:00Z' },
  { id: 'rev-5', author: 'Priya S.', rating: 5, body: 'Finally a brand that makes clothes for real women. The sizing is true and the quality is exceptional. I am obsessed with everything I have ordered.', created_at: '2024-03-18T00:00:00Z' },
]

export const mockSiteSettings: SiteSettings = {
  id: 'settings-1',
  key: 'announcement_bar',
  is_enabled: true,
  message: 'Free shipping on orders over $150 · Use code WELCOME10 for 10% off your first order',
  link_url: '/shop',
  starts_at: null,
  expires_at: null,
  updated_at: '2024-03-01T00:00:00Z',
}

export const SIZES = ['XS', 'S', 'M', 'L', 'XL']
export const COLORS = ['Black', 'Ivory', 'Cream', 'Sand', 'Charcoal', 'Mocha', 'White']
